### ISSUE TITLE
`act_func` call in `problem/rl_env/brax_env.py:42` is causing an error.

### ISSUE THREAD

**Issue by djole** [EMI-Group/tensorneat#2]
Hi,
when calling `pipeline.show` on a Brax environment, there is an error complaining that we're giving it 4 arguments when 3  are requested. I think the `state` shouldn't be passed to the `act_func` function.

Best,
Djordje

**Comment by WLS2002** [comment]
Thank you very much for taking the time to identify this issue! I'll merge your pull request for solving this issue. Thanks a lot!
